# Generated by Django 5.0.2 on 2024-04-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture_form', '0003_alter_district_name_alter_program_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
