# Generated by Django 5.0.2 on 2024-04-22 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture_form', '0004_alter_district_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('district', models.ManyToManyField(to='capture_form.district')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capture_form.program')),
                ('state', models.ManyToManyField(to='capture_form.state')),
            ],
        ),
    ]
