# Generated by Django 5.0.2 on 2024-02-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
