# Generated by Django 5.0.2 on 2024-03-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
