# Generated by Django 5.0.2 on 2024-03-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contact_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='task_visibility',
            new_name='permissions',
        ),
    ]
