# Generated by Django 5.0.2 on 2024-03-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_rename_task_visibility_contact_permissions'),
        ('organizations', '0010_remove_company_billing_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
    ]
