# Generated by Django 5.0.2 on 2024-03-25 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_modified_crmuser_updated'),
        ('contacts', '0013_rename_photo_contact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='record_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.crmuser'),
        ),
    ]
