# Generated by Django 5.0.2 on 2024-03-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_contact_record_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mailing_country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='other_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
