# Generated by Django 5.0.2 on 2024-03-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_alter_contact_mailing_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='due_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
