# Generated by Django 5.0.2 on 2024-03-26 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_modified_crmuser_updated'),
        ('contacts', '0018_contactrecentlyviewed'),
        ('organizations', '0010_remove_company_billing_street'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrecentlyviewed',
            old_name='contact',
            new_name='contact_id',
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='assistant_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='assistant_phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='due_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='email_opted_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='fax',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='home_phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_photos/'),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='mailing_address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='mailing_city',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='mailing_country',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='mailing_postal_code',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='mailing_state',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='mobile_phone',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='other_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='other_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='other_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='other_phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='other_postal_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='other_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='permission',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='permissions',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='phone',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='prefix',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='recent_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='recent_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='record_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.crmuser'),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='tag_list',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='title',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrecentlyviewed',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactrecentlyviewed',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contactrecentlyviewed',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='authentication.crmuser'),
        ),
    ]
