# Generated by Django 5.0.2 on 2024-03-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_rename_contact_contactrecentlyviewed_contact_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrecentlyviewed',
            old_name='recent_updated',
            new_name='recent_activity',
        ),
        migrations.RemoveField(
            model_name='contactrecentlyviewed',
            name='recent_created',
        ),
    ]
