# Generated by Django 5.0.2 on 2024-03-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_rename_recent_updated_contactrecentlyviewed_recent_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrecentlyviewed',
            name='contact_id',
        ),
    ]
