# Generated by Django 5.0.2 on 2024-03-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_rename_recent_activity_contactrecentlyviewed_modified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactRecentlyViewed',
        ),
    ]
