# Generated by Django 5.0.2 on 2024-03-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0025_contactrecentlyviewed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactRecentlyViewed',
        ),
    ]
