# Generated by Django 5.0.2 on 2024-02-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lead_status', models.CharField(choices=[('OPEN-Contacted', 'OPEN-Contacted'), ('OPEN-NotContacted', 'OPEN-NotContacted')], max_length=150)),
                ('lead_created', models.DateTimeField(auto_now_add=True)),
                ('lead_owner', models.CharField(max_length=150)),
            ],
        ),
    ]
