# Generated by Django 5.0.2 on 2024-02-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('OPEN-NotContacted', 'OPEN-NotContacted'), ('OPEN-Contacted', 'OPEN-Contacted')], max_length=150),
        ),
    ]
