# Generated by Django 5.0.2 on 2024-03-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('converted', 'converted')], max_length=150),
        ),
    ]
