# Generated by Django 5.0.2 on 2024-03-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_lead_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
