# Generated by Django 5.0.2 on 2024-03-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0007_delete_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('lead_status', models.CharField(default='OPEN - Not Contacted', max_length=150)),
                ('user_responsible', models.CharField(max_length=150)),
                ('lead_rating', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_opted_out', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=150)),
                ('number_of_employees', models.CharField(max_length=50)),
                ('lead_source', models.CharField(default='Web', max_length=150)),
                ('mailing_address', models.TextField()),
                ('mailing_city', models.CharField(blank=True, max_length=50, null=True)),
                ('mailing_state', models.CharField(blank=True, max_length=50, null=True)),
                ('mailing_postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('mailing_country', models.CharField(blank=True, default='India', max_length=100, null=True)),
                ('description', models.TextField()),
                ('tag_list', models.CharField(max_length=150)),
                ('permission', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_created', models.DateTimeField(auto_now_add=True)),
                ('lead_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
