# Generated by Django 5.0.2 on 2024-03-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_lead_description_alter_lead_lead_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='lead_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='lead_modified',
            new_name='updated',
        ),
    ]
