# Generated by Django 5.0.2 on 2024-03-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_rename_lead_created_lead_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
