# Generated by Django 5.0.2 on 2024-03-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
