# Generated by Django 5.0.2 on 2024-03-14 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_crmuser_address_crmuser_address_city_and_more'),
        ('leads', '0017_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_owner', to='authentication.crmuser'),
        ),
    ]
