# Generated by Django 5.0.2 on 2024-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_alter_lead_user_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(max_length=150),
        ),
    ]
