# Generated by Django 5.0.2 on 2024-03-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_alter_lead_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lead_images/'),
        ),
    ]
