# Generated by Django 5.0.2 on 2024-03-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_alter_lead_email_alter_lead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='record_owner',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
