# Generated by Django 5.0.2 on 2024-03-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_lead_record_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(default='Not Contacted', max_length=150),
        ),
    ]
