# Generated by Django 5.0.2 on 2024-03-30 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_modified_crmuser_updated'),
        ('leads', '0025_alter_lead_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='record_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.crmuser'),
        ),
    ]
