# Generated by Django 5.0.2 on 2024-04-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_alter_lead_record_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
