# Generated by Django 5.0.2 on 2024-04-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_alter_lead_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='record_owner',
        ),
        migrations.AlterField(
            model_name='lead',
            name='mailing_country',
            field=models.CharField(max_length=100),
        ),
    ]
