# Generated by Django 5.0.2 on 2024-04-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_remove_lead_record_owner_alter_lead_mailing_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
