# Generated by Django 5.0.2 on 2024-04-19 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_alter_lead_last_name'),
        ('organizations', '0017_rename_company_object_companyrecentlyviewed_company_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
    ]
