# Generated by Django 5.0.2 on 2024-03-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(default='In Progress', max_length=150)),
                ('category', models.CharField(default='Email', max_length=150)),
                ('user_responsible', models.CharField(max_length=150)),
                ('pipeline', models.CharField(max_length=150)),
                ('stage', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('tag_list', models.CharField(max_length=250)),
                ('visibility', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
