# Generated by Django 5.0.2 on 2024-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_pipelinestage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='stage',
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.ManyToManyField(to='projects.pipelinestage'),
        ),
    ]
