# Generated by Django 5.0.2 on 2024-03-18 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_crmuser_email_alter_crmuser_passport_number_and_more'),
        ('projects', '0004_remove_project_stage_project_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.crmuser'),
        ),
    ]
