# Generated by Django 5.0.2 on 2024-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_user_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinestage',
            name='stage',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
