# Generated by Django 5.0.2 on 2024-03-20 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_pipelinestage_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
