# Generated by Django 5.0.2 on 2024-03-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_pipelinestage_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinestage',
            options={'ordering': ['-created']},
        ),
    ]
