# Generated by Django 5.0.2 on 2024-03-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_pipelinestage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinestage',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
