# Generated by Django 5.0.2 on 2024-04-03 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_modified_crmuser_updated'),
        ('projects', '0012_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='record_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='authentication.crmuser'),
        ),
    ]
