# Generated by Django 5.0.2 on 2024-03-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=150)),
                ('starting_date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('ending_date', models.DateField()),
                ('ending_time', models.TimeField()),
                ('busy_or_free', models.CharField(blank=True, default='Busy', max_length=150, null=True)),
                ('notes', models.TextField()),
                ('user_responsible', models.CharField(max_length=150)),
                ('deal_or_lead', models.CharField(max_length=150)),
                ('people', models.CharField(max_length=250)),
                ('organization', models.CharField(max_length=150)),
            ],
        ),
    ]
