# Generated by Django 5.0.2 on 2024-03-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='busy_or_free',
            new_name='availability',
        ),
    ]
