# Generated by Django 5.0.2 on 2024-02-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('forecast_close_date', models.DateTimeField()),
                ('user_responsible', models.CharField(max_length=150)),
                ('deal_value', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
