# Generated by Django 5.0.2 on 2024-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='forecast_close_date',
            field=models.DateField(),
        ),
    ]
