# Generated by Django 5.0.2 on 2024-03-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_initial'),
        ('organizations', '0010_remove_company_billing_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.company'),
        ),
    ]
