# Generated by Django 5.0.2 on 2024-03-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_alter_deal_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
