# Generated by Django 5.0.2 on 2024-03-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_alter_deal_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='actual_close_date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='forecast_close_date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
