# Generated by Django 5.0.2 on 2024-03-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_alter_deal_user_responsible'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='deal',
            name='stage',
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ManyToManyField(to='deals.pipelinestage'),
        ),
    ]
