# Generated by Django 5.0.2 on 2024-04-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_deal_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='bid_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='bid_type',
            field=models.CharField(blank=True, default='Fixed Bid', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='pipeline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='visibility',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
