# Generated by Django 5.0.2 on 2024-04-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_modified_crmuser_updated'),
        ('deals', '0012_alter_deal_bid_amount_alter_deal_bid_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='user_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.crmuser'),
        ),
    ]
