# Generated by Django 5.0.2 on 2024-04-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0014_remove_deal_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='tag_list',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
