# Generated by Django 5.0.2 on 2024-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0015_alter_deal_tag_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deal_images/'),
        ),
    ]
