# Generated by Django 5.0.2 on 2024-04-02 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_modified_crmuser_updated'),
        ('deals', '0017_deal_record_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='record_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_owner', to='authentication.crmuser'),
        ),
    ]
