# Generated by Django 5.0.2 on 2024-04-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0018_alter_deal_record_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='name',
        ),
        migrations.AddField(
            model_name='deal',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='email_opted_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='industry',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='mailing_address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='mailing_city',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='mailing_country',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='mailing_postal_code',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='mailing_state',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='number_of_employees',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='prefix',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='title',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='website',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
