# Generated by Django 5.0.2 on 2024-04-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0019_remove_deal_name_deal_email_deal_email_opted_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
