# Generated by Django 5.0.2 on 2024-02-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(verbose_name='Website')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=180, verbose_name='Address')),
                ('city', models.CharField(db_index=True, max_length=60, verbose_name='City')),
                ('state', models.CharField(db_index=True, max_length=30, verbose_name='State')),
                ('zipcode', models.CharField(max_length=40, verbose_name='Zip code')),
                ('country', models.CharField(default='India', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationcategory')),
            ],
        ),
    ]
