# Generated by Django 5.0.2 on 2024-02-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=25)),
                ('billing_street', models.CharField(max_length=150)),
                ('billing_state', models.CharField(max_length=150)),
                ('billing_country', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='OrganizationCategory',
            new_name='CompanyCategory',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
