# Generated by Django 5.0.2 on 2024-02-27 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_company_rename_organizationcategory_companycategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Organization',
        ),
        migrations.RenameModel(
            old_name='CompanyCategory',
            new_name='OrganizationCategory',
        ),
    ]
