# Generated by Django 5.0.2 on 2024-03-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_rename_company_organization_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Company',
        ),
        migrations.DeleteModel(
            name='OrganizationCategory',
        ),
    ]
