# Generated by Django 5.0.2 on 2024-03-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_rename_organization_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
