# Generated by Django 5.0.2 on 2024-03-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('organization', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=25)),
                ('fax', models.CharField(max_length=25)),
                ('website', models.CharField(max_length=150)),
                ('linkedin', models.CharField(max_length=150)),
                ('facebook', models.CharField(max_length=150)),
                ('twitter', models.CharField(max_length=150)),
                ('email_domains', models.CharField(max_length=250)),
                ('billing_address', models.TextField()),
                ('billing_street', models.CharField(max_length=150)),
                ('billing_city', models.CharField(max_length=150)),
                ('billing_state', models.CharField(max_length=150)),
                ('billing_postal_code', models.CharField(max_length=25)),
                ('billing_country', models.CharField(default='India', max_length=150)),
                ('shipping_address', models.TextField()),
                ('shipping_city', models.CharField(max_length=150)),
                ('shipping_state', models.CharField(max_length=150)),
                ('shipping_postal_code', models.CharField(max_length=25)),
                ('shipping_country', models.CharField(default='India', max_length=150)),
                ('date_to_remember', models.DateField()),
                ('description', models.TextField()),
                ('tag_list', models.CharField(max_length=250)),
                ('permission', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
