# Generated by Django 5.0.2 on 2024-03-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_company_date_to_remember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
