# Generated by Django 5.0.2 on 2024-03-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_company_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='billing_street',
        ),
    ]
