# Generated by Django 5.0.2 on 2024-03-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='record_owner',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
