# Generated by Django 5.0.2 on 2024-04-08 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_alter_company_record_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('Company_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_recently_viewed', to='organizations.company')),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_recently_viewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
