# Generated by Django 5.0.2 on 2024-04-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_companyrecentlyviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyrecentlyviewed',
            old_name='Company_object',
            new_name='company_object',
        ),
    ]
