# Generated by Django 5.0.2 on 2024-02-26 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_crmuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
