# Generated by Django 5.0.2 on 2024-03-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_crmuser_email_alter_crmuser_passport_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crmuser',
            old_name='modified',
            new_name='updated',
        ),
    ]
