# Generated by Django 5.0.2 on 2024-04-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_modified_crmuser_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='name',
        ),
    ]
