# Generated by Django 5.0.2 on 2024-04-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_crmuser_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crm_user_images/'),
        ),
    ]
