# Generated by Django 5.0.2 on 2024-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_crmuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crmuser',
            old_name='priamry_contact_phone',
            new_name='priamry_contact_phone1',
        ),
        migrations.RenameField(
            model_name='crmuser',
            old_name='secondary_contact_phone',
            new_name='priamry_contact_phone2',
        ),
        migrations.AddField(
            model_name='crmuser',
            name='secondary_contact_phone1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crmuser',
            name='secondary_contact_phone2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
