# Generated by Django 5.0.2 on 2024-04-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_rename_priamry_contact_phone_crmuser_priamry_contact_phone1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crmuser',
            old_name='priamry_contact_phone1',
            new_name='primary_contact_phone1',
        ),
        migrations.RenameField(
            model_name='crmuser',
            old_name='priamry_contact_phone2',
            new_name='primary_contact_phone2',
        ),
    ]
