# Generated by Django 5.0.2 on 2024-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_rename_priamry_contact_phone1_crmuser_primary_contact_phone1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='education_info',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='experience',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='family_info',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
