# Generated by Django 5.0.2 on 2024-04-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_crmuser_education_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmuser',
            name='education_info',
        ),
    ]
