# Generated by Django 5.0.2 on 2024-04-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_crmuser_education_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmUserEducationInformation',
            fields=[
                ('crm_user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('started_year', models.CharField(max_length=50)),
                ('completed_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CrmUserExperience',
            fields=[
                ('crm_user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('stated_month_and_year', models.CharField(max_length=50)),
                ('completed_month_and_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CrmUserFamilyInformation',
            fields=[
                ('crm_user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
