# Generated by Django 5.0.2 on 2024-04-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_crmusereducationinformation_crmuserexperience_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrmUserEducationInformation',
            new_name='CrmUserEducation',
        ),
    ]
