# Generated by Django 5.0.2 on 2024-04-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_rename_crmusereducationinformation_crmusereducation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmuser',
            name='education_info',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='family_info',
        ),
        migrations.AddField(
            model_name='crmuser',
            name='education_info',
            field=models.ManyToManyField(to='authentication.crmusereducation'),
        ),
        migrations.AddField(
            model_name='crmuser',
            name='experience',
            field=models.ManyToManyField(to='authentication.crmuserexperience'),
        ),
        migrations.AddField(
            model_name='crmuser',
            name='family_info',
            field=models.ManyToManyField(to='authentication.crmuserfamilyinformation'),
        ),
    ]
