# Generated by Django 5.0.2 on 2024-04-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_remove_crmuser_education_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmuser',
            name='education_info',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='family_info',
        ),
        migrations.DeleteModel(
            name='CrmUserEducation',
        ),
        migrations.AddField(
            model_name='crmuser',
            name='education_info',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='CrmUserExperience',
        ),
        migrations.AddField(
            model_name='crmuser',
            name='experience',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='CrmUserFamilyInformation',
        ),
        migrations.AddField(
            model_name='crmuser',
            name='family_info',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
