# Generated by Django 5.0.2 on 2024-04-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_remove_crmuser_education_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmUserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_user_id', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('started_year', models.CharField(max_length=50)),
                ('completed_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CrmUserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_user_id', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('stated_month_and_year', models.CharField(max_length=50)),
                ('completed_month_and_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CrmUserFamilyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='education_info',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='family_info',
        ),
        migrations.AddField(
            model_name='crmuser',
            name='education_info',
            field=models.ManyToManyField(to='authentication.crmusereducation'),
        ),
        migrations.AddField(
            model_name='crmuser',
            name='experience',
            field=models.ManyToManyField(to='authentication.crmuserexperience'),
        ),
        migrations.AddField(
            model_name='crmuser',
            name='family_info',
            field=models.ManyToManyField(to='authentication.crmuserfamilyinformation'),
        ),
    ]
