# Generated by Django 5.0.2 on 2024-04-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_crmusereducation_crmuserexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmuserfamilyinformation',
            name='relationship',
            field=models.CharField(default='Sibling', max_length=150),
            preserve_default=False,
        ),
    ]
