# Generated by Django 5.0.2 on 2024-04-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_crmusereducation_completed_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmusereducation',
            options={'ordering': ['started_year']},
        ),
        migrations.RenameField(
            model_name='crmuserexperience',
            old_name='completed_month_and_year',
            new_name='started_year',
        ),
        migrations.RenameField(
            model_name='crmuserexperience',
            old_name='stated_month_and_year',
            new_name='stated_month',
        ),
        migrations.AddField(
            model_name='crmuserexperience',
            name='completed_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crmuserexperience',
            name='completed_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
