# Generated by Django 5.0.2 on 2024-04-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_rename_completed_month_crmuserexperience_completed_month_and_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmuser',
            name='team',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
