# Generated by Django 5.0.2 on 2024-04-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_alter_crmuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.crmuser'),
        ),
    ]
