# Generated by Django 5.0.2 on 2024-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('percentage_completed', models.PositiveIntegerField()),
                ('responsible_user', models.CharField(max_length=150)),
                ('due_date', models.DateField()),
                ('task_owner', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Started', 'Started')], max_length=150)),
            ],
        ),
    ]
