# Generated by Django 5.0.2 on 2024-03-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
