# Generated by Django 5.0.2 on 2024-03-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0007_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('due_date', models.DateField()),
                ('start_date', models.DateField()),
                ('reminder_date', models.DateField()),
                ('progress', models.CharField(max_length=150)),
                ('priority', models.CharField(max_length=150)),
                ('status', models.CharField(default='Not Started', max_length=150)),
                ('related_to', models.CharField(default='Not Started', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('permission', models.CharField(max_length=150)),
                ('percentage_completed', models.PositiveIntegerField(default=0)),
                ('task_owner', models.CharField(max_length=150)),
            ],
        ),
    ]
