# Generated by Django 5.0.2 on 2024-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(blank=True, default='Me', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, default='Email', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, default='Low', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='related_to',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
