# Generated by Django 5.0.2 on 2024-03-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_due_date_alter_task_reminder_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
