# Generated by Django 5.0.2 on 2024-03-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_created_at_task_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
