# Generated by Django 5.0.2 on 2024-03-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_rename_created_at_task_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='permission',
        ),
    ]
