# Generated by Django 5.0.2 on 2024-03-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_task_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='permission',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
