# Generated by Django 5.0.2 on 2024-04-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
