# Generated by Django 5.0.2 on 2024-04-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_alter_task_assigned_to_alter_task_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='permission',
            new_name='tast_visibility',
        ),
    ]
